version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: monpassword
      POSTGRES_DB: madatabase
    networks:
      - pgreseaux
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - pgreseaux

networks:
  pgreseaux:

volumes:
  pgdata:
